title: Mero
tagline: Pure, simple &amp; genuine.
description: >- # this means to ignore newlines until "baseurl:"
    Enter a short description for your blog here.
baseurl: "" # the subpath of your site, e.g. /blog
timezone: PT
permalink: /:slug
url: https://yourdomainname.com # the base hostname & protocol for your site, e.g. http://example.com
google_analytics_id: UA-AAAAAAAA-2

# Code snippets syntax highlight
highlighter: rouge

# Archives / Category pages
jekyll-archives:
    enabled: [categories]
    layout: category
    permalinks:
        category: "/category/:name/"

# Pagination
pagination:
    enabled: true
    per_page: 12
    title: ""
    permalink: "/page/:num/"
    trail:
        before: 2
        after: 2
    sort_field: "date"
    sort_reverse: true

# SEO Tag data
author:
    name: Your Name
    twitter: yourTwitter
    website: https://yourdomainname.com
    email: you@yourdomainname.com
logo: /assets/images/open_graph.png
twitter:
    username: yourTwitter
    card: summary_large_image
social:
    name: Your Name
    links:
        - https://github.com/yourGitHub
        - https://twitter.com/yourTwitter

# Default front matter
defaults:
    - scope:
          path: ""
      values:
          image:
              path: /assets/images/open_graph.png
              width: 1024
              height: 500

# Build settings
markdown: kramdown
plugins:
    - jekyll-paginate-v2
    - jekyll-archives

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
    - Gemfile
    - Gemfile.lock
    - node_modules
    - package.json
    - assets/javascript/*.es6.js
    - assets/javascript/index.js
    - webpack.config.js
    - screenshots
